import { execSync } from "node:child_process";
import { createRequire } from "node:module";
import path from "node:path";
execSync("npx tsc lib/structural/seismic.ts --outDir .tmp-sq --module commonjs --target es2020 --skipLibCheck --esModuleInterop", { stdio: "inherit" });
const req = createRequire(import.meta.url);
const { spectrum, baseShear, CITY_DEFAULTS } = req(path.join(process.cwd(), ".tmp-sq", "seismic.js"));
let pass = 0, fail = 0; const check = (l, ok) => { console.log(`${ok ? "✓" : "✗"} ${l}`); ok ? pass++ : fail++; };
const bog = CITY_DEFAULTS["Bogota D.C."];
const s = spectrum(bog);
check("T0 = 0.1*AvFv/AaFa", Math.abs(s.T0 - 0.1 * (0.3 * 1.7) / (0.25 * 1.3)) < 0.005);
check("TL = 2.4*Fv", s.TL === 2.4 * 1.7);
const plateau = 2.5 * bog.Aa * bog.Fa * 1.0;
check("meseta en T0..TC = 2.5AaFaI", Math.abs(s.Sa((s.T0 + s.TC) / 2) - plateau) < 1e-9);
check("rampa en T=0 = 0.4*meseta", Math.abs(s.Sa(0) - 0.4 * plateau) < 1e-9);
check("rama 1/T decrece", s.Sa(s.TC * 1.2) < plateau && s.Sa(1.5) < s.Sa(1.0));
check("crece en rampa hasta T0 y luego no crece", s.Sa(0.05) < s.Sa(0.15) && s.Sa(0.15) <= s.Sa(s.T0) && [0.2, 0.5, 1, 2].every((T, i, a) => i === 0 || s.Sa(T) <= s.Sa(a[i - 1]) + 1e-9));
const v = baseShear(bog, 0.2, 33000);
check("Vs = Sa*W*I/R (COP corte)", Math.abs(v.Vs_kgf - (v.Sa * 33000) / 7) < 50);
console.log(`\n${pass} pasan · ${fail} fallan — Bogota: T0=${s.T0} TC=${s.TC} TL=${s.TL} | Sa(0.2)=${v.Sa}g | Vs=${Math.round(v.Vs_kgf / 1000)}t`);
process.exit(fail ? 1 : 0);
